In [86]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [87]:
df = pd.read_csv('Churn_Modelling.csv')

In [88]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

## preprocessing

In [89]:
# delete the RowNumber, CustomerId, Surname
df = df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [90]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [91]:
## Encode categorical variables
label_encoder_gender = LabelEncoder()
df['Gender'] = label_encoder_gender.fit_transform(df['Gender'])
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [92]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [93]:
## Onehot encoder for Geography columns
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder = OneHotEncoder(sparse_output=False)
geo_onehot_encoder = one_hot_encoder.fit_transform(df[['Geography']])
geo_onehot_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [94]:
columns = one_hot_encoder.get_feature_names_out(['Geography'])

In [95]:
geo_encoded_df = pd.DataFrame(geo_onehot_encoder, columns=columns)

In [96]:
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [97]:
## Combine one hot encoded geography field with original df
df = pd.concat([df.drop('Geography', axis=1), geo_encoded_df], axis=1)

In [84]:
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [98]:
type(one_hot_encoder)

sklearn.preprocessing._encoders.OneHotEncoder

In [99]:
## Save the encoders and scaler
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(one_hot_encoder, file)

In [64]:
## divide the dataset into dependent and independent features
X = df.drop('Exited', axis=1)
y = df['Exited']

In [65]:
type(y)

pandas.Series

In [66]:
## split the data into train test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [67]:
## scale these fearures
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [68]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [69]:
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

## ANN Implementation

In [70]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard

In [71]:
## Build ANN model
model = Sequential([
    Dense(64, activation='relu', input_shape = (X_train.shape[1],)), ## Hidden layer 1 connected with input layer
    Dense(32, activation='relu'), # HL2 
    Dense(1, activation='sigmoid') # output layer
])

/Users/ashishbutola/Ashish-Butola/Up_Skilling/Udemy-Machine-learning/deep_learning/annclassification/deep-learning/lib/python3.12/site-packages/keras/src/layers/core/dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [72]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [73]:
optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)
loss = tf.keras.losses.BinaryCrossentropy()

In [74]:
# compile the model
model.compile(optimizer=optimizer, loss=loss, metrics=['accuracy'])

In [75]:
## set up tensorboard
import datetime
logs_dir = f"logs/fit/{datetime.datetime.now().strftime("%Y%m%d-%H%M%S")}"

In [76]:
tensorflow_callback = TensorBoard(log_dir=logs_dir, histogram_freq=1)

In [77]:
## set up early stopping
early_stop_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

## Train the model

In [78]:
history = model.fit(
    X_train, y_train, validation_data = (X_test, y_test), epochs = 100,
    callbacks=[tensorflow_callback, early_stop_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8347 - loss: 0.3960 - val_accuracy: 0.8525 - val_loss: 0.3503
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8536 - loss: 0.3523 - val_accuracy: 0.8605 - val_loss: 0.3418
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 981us/step - accuracy: 0.8574 - loss: 0.3460 - val_accuracy: 0.8465 - val_loss: 0.3672
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 974us/step - accuracy: 0.8600 - loss: 0.3449 - val_accuracy: 0.8605 - val_loss: 0.3383
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8625 - loss: 0.3410 - val_accuracy: 0.8585 - val_loss: 0.3399
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8624 - loss: 0.3385 - val_accuracy: 0.8570 - val_loss: 0.3552
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8633 - loss: 0.3338 - val_accuracy: 0.8620 - val_loss: 0.3399
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 995us/step - accuracy: 0.8637 - loss: 0.3322 - val_accuracy: 0.8565 - val_loss: 0.3659
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 0.8652 - loss: 0.3309 - val_accuracy: 0.8580 - val_loss: 0.3500
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.8664 - loss: 0.3263 - val_accuracy: 0.8580 - val_loss: 0.3428
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 954us/step - accuracy: 0.8652 - loss: 0.3287 - val_accuracy: 0.8610 - val_loss: 0.3441
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.8670 - loss: 0.3243 - val_accuracy: 0.8515 - val_loss: 0.3467
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.8687 - loss: 0.3193 - val_accuracy: 0.8610 - val_loss: 0.3457
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 940us/step - accuracy: 0.8691 - loss: 0.3196 - val_accuracy: 0.8555 - val_loss: 0.3487

In [79]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [80]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [81]:
%tensorboard --logdir logs/fit/20260614-124024

Reusing TensorBoard on port 6006 (pid 7461), started 0:23:06 ago. (Use '!kill 7461' to kill it.)

In [82]:
# !pip install setuptools

In [83]:
# Load the pickle file